### ISSUE TITLE
Home batteries and cars and and and... ;-)

### ISSUE THREAD

**Issue by heggink** [Olli69/powerguru#1]
Hej Olli,

I am looking for a piece of software to automate the electricity side of my household. Soon (2 weeks) I will be in dynamic enery pricing. Soon, (couple of months) I am looking to upgrade my solar panels, add another electrc car, install my electric water heater, consider installing a home battery. In that sense, I was looking for something that can schedule the right actions based on power availability (battery, solar panels, grid), price and required consumption taking into account required vs available power so to not overload anything.

Does Powerguru provide a decent basis for that? Interested to hear what is still missing.

KR,

Herman Eggink
firstname dot lastname at outlook.com

**Comment by Olli69** [comment]
Hello Herman,
Please have a look at current ESP32 based project [Arska](https://github.com/Netgalleria/arska-node). Basically, you can do relay controlling rules based on different kinds of input; price based values, measured net import/export, time/date.  Solar weather forecast is currently available in Finland. 

BR,
Olli

**Comment by heggink** [comment]
Hey Olli,

Many thanks. Is the arska.js the central piece and you wrote that?

Currently, I run domoticz as my automation vehicle. In that light, this facility would need to integrate there rather than thru GPIO but that should be fine. That said, I would be quite in favoiur of having a docker type solution instead of an ESP based. I understand the ESP requirement if you need to use GPIO but most systems have some 'external' interface (web, modbus, ..).

Do you think that code is adaptable to achieve that? I have seen systems like BLIQ but these are typically very limited to controlling home batteries in relation to energy rates AND cost (quite some) money. A good open source algorithm would be brilliant.

H

**Comment by Olli69** [comment]
Hi,
Arska.js is a main part of UI (will be updated...) but the logic is in main.cpp (C/C++) . 

The idea of Arska is to be a lean box that can control (independently, without home automation) eg. boilers (contactor control), heat pumps (with relay input), etc. It could also control batteries with relay input if charging/discharging info would be enough for the battery. There have been discussions, but I do not know if anybody has used it with batteries yet. In addition to GPIO, it can control also Tasmota and Shelly relays. 

Olli
PS. A note to anybody who is reading this possibly later:  I'm talking about [Arska](https://github.com/Netgalleria/arska-node) repo, not this one.
